### ISSUE TITLE
Add SPIFFS access?

### ISSUE THREAD

**Issue by LukinoCZ** [boblemaire/ESPAsyncSDWebServer#3]
How to change SD file load function for use SPIFFS? I would like to have web pages on SPIFFS and TXT log files on SD card.

Thanks

**Comment by boblemaire** [comment]
Sorry, can't help you there.  Asyncwebserver natively uses SPIFFS, but there are some conflicts in the use of FS class for both that can be resolved in favor of either but not both.  You may be able to roll your own SPIFFS on top of this SD adaptation, but I just don't have the experience with SPIFFS to help you.
The good news is that they have eliminated the conflicts on the ESP32 allowing access to both, and using the fast SD access protocols at 25mhz.  Last time I checked there was no formal web server available yet for that, but it's on the short list.
I'm going to close this as it's beyond the design functionality of this code.  Good luck.
